### ISSUE TITLE
add custom background  use  

### ISSUE THREAD

**Issue by Alaabadr44** [hasanmhallak/date_picker#17]

**Comment by hasanmhallak** [comment]
The DatePicker widget does not enforce a specific background color, meaning it displays whatever color is present underneath the widget because its surface is transparent. To modify the background color, you can simply change the underlying material by wrapping a Material widget with the desired color around the DatePicker widget. For example, you can set the background color of the Scaffold. Therefore, I'll be closing this issue as invalid.
